### ISSUE TITLE
Filters: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by bolus** [pugjs/react-jade#64]
It seems it's not possible to use filters.

No matter what I do I always get a 'undefined is not a function' error (see the end of this message for the full error message).

I've installed different  jstransformer packages but I always get the same error.

If I remove the filter then the error disappears.

The following code reproduces the error:

jade.compile("\nh1 foo\n\n:rho\n    foo\n", filename: "foo.jade")

The full error message:

```
TypeError: undefined is not a function
    at Compiler.visit (/Users/dah/Projects/sites/ahrin.de/meteor-app/app/private/gulp/node_modules/react-jade/lib/utils/compiler.js:47:35)
    at Compiler.visitBlock (/Users/dah/Projects/sites/ahrin.de/meteor-app/app/private/gulp/node_modules/react-jade/lib/utils/compiler.js:51:10)
    at Compiler.visit (/Users/dah/Projects/sites/ahrin.de/meteor-app/app/private/gulp/node_modules/react-jade/lib/utils/compiler.js:47:35)
    at Compiler.compile (/Users/dah/Projects/sites/ahrin.de/meteor-app/app/private/gulp/node_modules/react-jade/lib/utils/compiler.js:28:8)
    at parse (/Users/dah/Projects/sites/ahrin.de/meteor-app/app/private/gulp/node_modules/react-jade/lib/parse.js:30:22)
    at Function.compile (/Users/dah/Projects/sites/ahrin.de/meteor-app/app/private/gulp/node_modules/react-jade/lib/compile.js:9:28)
    at Object.<anonymous> (/Users/dah/Projects/sites/ahrin.de/meteor-app/app/private/gulp/gulpfile.js:29:8)
    at Object.<anonymous> (/Users/dah/Projects/sites/ahrin.de/meteor-app/app/private/gulp/gulpfile.js:120:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by bolus** [comment]
It seems filters are not implemented yet. This is missing in the "Unsupported Features" section

**Comment by ForbesLindesay** [comment]
Hi, I'm sorry I didn't manage to resolve this issue.  I've now replaced this project with https://github.com/pugjs/babel-plugin-transform-react-pug so I won't be looking at any of these outstanding issues.
